---
fullname: Parsec
shortname: coq-parsec
opam_name: coq-parsec
organization: liyishuai
action: true
ci_test_dependants: true
synopsis: Monadic parser combinator library in Coq
description: Inspired by Haskell Parsec library.
authors:
  - name: Yishuai Li
    email: yishuai@cis.upenn.edu
    orcid: 0000-0002-5728-5903
  - name: Azzam Althagafi
    email: aazzam@cis.upenn.edu
  - name: Yao Li
    email: liyao@cis.upenn.edu
    orcid: 0000-0001-8720-883X
  - name: Li-yao Xia
    email: xialiyao@cis.upenn.edu
    orcid: 0000-0003-2673-4400
  - name: Benjamin C. Pierce
    email: bcpierce@cis.upenn.edu
    orcid: 0000-0001-7839-1636
license:
  - fullname: BSD 3-Clause "New" or "Revised" License
    identifier: BSD-3-Clause
dependencies:
  - description: '[Cérès](https://github.com/Lysxia/coq-ceres)'
    opam:
      name: coq-ceres
      version: '{ >= "0.4.0" }'
  - description: '[ExtLib](https://coq-community.org/coq-ext-lib/)'
    opam:
      name: coq-ext-lib
      version: '{ >= "0.11.3" }'
test_target: test
categories:
  - name: Computer Science/Data Types and Data Structures
keywords:
  - name: string
namespace: Parsec
opam-file-maintainer: 'Yishuai Li <liyishuai.lys@alibaba-inc.com>'
supported_coq_versions:
  text: 8.14 or later
  opam: '{ >= "8.14~" }'
tested_coq_opam_versions:
  - version: 'dev'
  - version: '8.14'
  - version: '8.15'
  - version: '8.16'
  - version: '8.17'
  - version: '8.18'
